import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Aditi Ashok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>
            Aditi's Front End Web Programming Page
          </h1>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/aditi_pic.jpg"
            alt="Next.js Logo"
            width={300}
            height={300}
            priority
          />
        </div>
        
    
      </main>
    </>
  )
}
