import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Aditi Ashok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>
            Gallery
          </h1>
        </div>

        <a
        href="https://aditi-ashok.github.io/lab-04"
        className={styles.card}
        target="_blank"
        rel="noopener noreferrer"
        >
        <h2 className={inter.className}>
            HR Directory <span>-&gt;</span>
        </h2>
        <p className={inter.className}>
            Loads an HR Directory from a CSV file
        </p>
        </a>

        <a
        href="https://aditi-ashok.github.io/lab-05"
        className={styles.card}
        target="_blank"
        rel="noopener noreferrer"
        >
        <h2 className={inter.className}>
           Simple To-Do List <span>-&gt;</span>
        </h2>
        <p className={inter.className}>
            Creates a simple to-do list
        </p>
        </a>



    <a
        href="/"
        className={styles.card}
        target="_blank"
        rel="noopener noreferrer"
        >
        <h2 className={inter.className}>
            Home <span>-&gt;</span>
        </h2>
        <p className={inter.className}>
            Back to homepage
        </p>
        </a>

      </main>
    </>
  )
}

